
// Testar a criação e envio de uma tarefa (POST)

POST http://localhost:3000/task
Content-Type: application/json

{
  "name": "Treinar domingo",
  "date": "2024-11-24",
  "category": "treino",
  "completed": "false"
}
